version: '3.8'

services:
  backend:
    build:
      context: ./backendapi
    ports:
      - "5039:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - frontend

  frontend:
    build:
      context: ./board-frontend
    ports:
      - "3000:80"